[package]
name = "rlalloc"
version = "0.1.1"
edition = "2021"
description = "blazingly slow malloc replacement"
license = "MIT"
repository = "https://github.com/Robert4S/ralloc/"

[dependencies]
itertools = "0.13.0"
itoa = "1.0.11"
libc = "0.2.155"
parking_lot = "0.12.3"
