[package]
name = "rlalloc"
version = "0.1.2"
edition = "2021"
description = "blazingly slow malloc replacement"
license = "MIT"
repository = "https://github.com/Robert4S/ralloc/"

[dependencies]
itoa = "1.0.11"
parking_lot = "0.12.3"
